---
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: deno --version
      - run: deno cache --reload --lock=lock.json test/deps.ts
      - run: deno test
      - run: mkdir node_modules
      - run: ./bin/lint
      - run: ./scripts/lint.ts
