---
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno --version
          ./scripts/lint.ts
          deno test
      # - run: bash <(curl -s https://codecov.io/bash)
      #   env:
      #     CODECOV_TOKEN: 5183f977-3ea8-48b1-87a0-0a5114afabf0
