---
name: Node.js CI

on: [push]

env:
  CI: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }} # delete this when it is public
          submodules: recursive

  build:
    needs: setup
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version: [10.x, 12.x, 14.x, 15.x]
        architecture: [x64]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }} # delete this when it is public
          submodules: recursive

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}

      - run: npm ci
      - run: npm test --collectCoverage

      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 5183f977-3ea8-48b1-87a0-0a5114afabf0

      - run: |
          npm link
          cd example
          npm link oclip
          npm ci
          npx ts-node src/commands/kill.ts -v 20000
          npm pack
          yarn pack
          tar -xvzf oclip-example-*.tgz
          ./package/bin/run serve 20000
