---
name: Node.js CI

on: [push]

env:
  CI: true

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
      - run: npm test

  test:
    needs: canary
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        # node_version: [10.x, 12.x, 14.x, 15.x]
        node_version: [10.x, 15.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }} # delete this when it is public
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm ci

      - if: ${{ matrix.node_version == '15.x' && matrix.os == 'ubuntu-latest' }}
        run: |
          npm test --collectCoverage
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 5183f977-3ea8-48b1-87a0-0a5114afabf0
      - if: ${{ matrix.node_version != '15.x' }}
        run: npm test

  lint:
    needs: canary
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }} # delete this when it is public
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm ci
      - run: npm run lint

  e2e:
    needs: canary
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }} # delete this when it is public
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm ci
      - run: npm link
      - run: |
          npm link oclip
          npm ci
        working-directory: example
      - run: npx ts-node src/cli.ts 20000
        working-directory: example
      - run: |
          npm pack
          tar -xvzf oclip-example-*.tgz
        working-directory: example
      - run: ./package/bin/run serve 20000
        working-directory: example

  release:
    needs: [test, lint, e2e]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }} # delete this when it is public
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: echo npm publish xxxxxxx
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
