---
name: Node.js CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          # - macos-latest
          # - windows-latest
        # node_version: [12.x, 14.x, 15.x]
        node_version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }} # delete this when it is public
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: v1-${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v1-${{ runner.OS }}-node-
            v1-${{ runner.OS }}-
      - run: npm ci
      - run: npm test -- --ci --coverage
        env:
          CI: true
      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: 5183f977-3ea8-48b1-87a0-0a5114afabf0
      - run: npm run lint

      - run: npm link
      - id: oclip-example-version
        run: echo "::set-output name=version::$(npm view oclip-example version)"
        working-directory: example
      - run: |
          npm link oclip
          npm ci
          npx ts-node src/cli.ts 20000
          npm pack
          tar -xvzf oclip-example-${{steps.oclip-example-version.outputs.version}}.tgz
          ./package/bin/cli.js serve 20000
        working-directory: example

  release:
    runs-on: ubuntu-20.04
    needs: test
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: v1-${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v1-${{ runner.OS }}-node-
            v1-${{ runner.OS }}-

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     # body: |
      #     #   Changes in this Release
      #     #   - First Change
      #     #   - Second Change
      #     draft: true
      #     prerelease: false

      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - uses: actions/setup-node@v2
      #   with:
      #     registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
